name: Deploy GitBook to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (Use v14 for compatibility)
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install GitBook CLI
        run: npm install -g gitbook-cli --legacy-peer-deps

      - name: Install GitBook plugins and build
        run: |
          gitbook install
          gitbook build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gitbook-site
          path: _book
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: gitbook-site
          path: _book

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
